name: "AccessDB Diff"
description: "Generate diffs for accessdb files"

outputs:
  has-accdb-files:
    description: "True if accdb files were found"
    value: ${{ steps.list-accdb-files.outputs.has-accdb-files }}
  accdb-diffs:
    description: "Text of accdb diff"
    value: ${{ steps.generate-accdb-diff.outputs.accdb-diffs }}

runs:
  using: "composite"
  steps:
    - id: list-accdb-files
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        added=$(${{ github.action_path }}/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "A" )
        modified=$(${{ github.action_path }}/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "M" )
        result="$added $modified"
        if [ -n "$result" ]
        then 
          echo "HAS_ACCDB_FILES=true" >> $GITHUB_ENV
          echo "::set-output name=has_accdb_files::true" 
        else          
          echo "HAS_ACCDB_FILES=false" >> $GITHUB_ENV
          echo "::set-output name=has_accdb_files::false" 
        fi
        echo "::debug::$result"
      shell: bash

    - id: install-mdbtools
      run: |
        sudo apt --assume-yes install mdbtools
      shell: bash

    - id: install-csvtojson
      run: |
        sudo npm i -g csvtojson
      shell: bash

    - id: generate-accdb-diff
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        echo "V: 024"
        echo "::debug::$(${{ github.action_path }}/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "A" )"
        echo "::debug::$(${{ github.action_path }}/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "M" )"
        result=$(${{ github.action_path }}/diff-accdb-files.sh \
                ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }})

        echo "::set-output name=accdb-diffs::${result}"
      shell: bash
