name: "AccessDB Diff"
description: "Generate diffs for accessdb files"

outputs:
  has-accdb-files:
    description: "True if accdb files were found"
    value: ${{ steps.list-accdb-files.outputs.has-accdb-files }}
  accdb-diff:
    description: "Text of accdb diff"
    value: ${{ steps.generate-accdb-diff.outputs.accdb-diff }}

runs:
  using: "composite"
  steps:
    - id: list-accdb-files
      run: |
        added=$(${{ github.action_path }}/.github/workflows/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "A" )
        modified=$(${{ github.action_path }}/.github/workflows/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "M" )
        result="$added $modified"
        if [ -n "$result" ]; then echo "::set-output name=has-accdb-files::$result" ; fi;
        if [ -n "$result" ]
        then 
          echo "HAS_ACCDB_FILES=true" >> $GITHUB_ENV
        else 
          echo "HAS_ACCDB_FILES=false" >> $GITHUB_ENV
        fi
      shell: bash

    - id: install-mdbtools
      run: |
        if [ ${{ env.HAS_ACCDB_FILES }} = true ]
        then
          sudo apt update
          sudo apt --assume-yes install mdbtools
        fi
      shell: bash

    - id: install-csvtojson
      run: |
        if [ ${{ env.HAS_ACCDB_FILES }} = true ]
         then
           sudo npm i -g csvtojson
         fi
      shell: bash

    - id: generate-accdb-diff
      run: |
        if [ ${{ env.HAS_ACCDB_FILES }} = true ]
         then
           result=$(${{ github.action_path }}/.github/workflows/diff-accdb-files.sh \
             ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} \
             | ${{ github.action_path }}/.github/workflows/convert-to-markdown-comment.sh \
             | jq --slurp --raw-input '.')
           echo "::set-output name=accdb-diff::$result"
         fi
      shell: bash
