name: Diff AccessDB
on: [push, pull_request]

jobs:
  generate-diffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x

      - name: Build API project
        run: dotnet publish $GITHUB_WORKSPACE/SolutionCliTools/ -o $GITHUB_WORKSPACE/bin -c release -r ubuntu.18.04-x64 --self-contained

      - name: Install OLEDB
        run: |
          sudo su
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

          #Download appropriate package for the OS version
          #Choose only ONE of the following, corresponding to your OS version

          #Ubuntu 18.04
          curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list >  $GITHUB_WORKSPACE/etc/apt/sources.list.d/mssql-release.list

          exit
          # apt-get update
          # ACCEPT_EULA=Y apt-get install -y msodbcsql17
          # # optional: for bcp and sqlcmd
          # ACCEPT_EULA=Y apt-get install -y mssql-tools
          # echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> $GITHUB_WORKSPACE/.bashrc
          # source $GITHUB_WORKSPACE/.bashrc
          # # optional: for unixODBC development headers
          # apt-get install -y unixodbc-dev

      - name: Find accessdb files
        id: access-files
        run: |
          $GITHUB_WORKSPACE/.github/workflows/command.sh ${{ github.event.pull_request.head.sha }}
        continue-on-error: true

