name: Diff AccessDB
on: [pull_request]

jobs:
  find-accdb-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List modified accdb files
        id: list-accdb-files
        run: |
          added=$(${{ github.workspace }}/.github/workflows/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "A" )
          modified=$(${{ github.workspace }}/.github/workflows/list-accdb-files.sh ${{ github.event.pull_request.head.sha }} "M" )
          result="$added $modified"
          if [ -n "$result" ]; then echo "::set-output name=hasAccdbFiles::true" ; fi;
          echo "::set-output name=accdbFiles::$result"

      - name: Install mdbtools
        id: install-mdbtools
        if: ${{ steps.list-accdb-files.outputs.hasAccdbFiles }}
        run: |
          sudo apt update
          sudo apt --assume-yes install mdbtools

      - name: Install csvtojson
        id: install-csvtojson
        if: ${{ steps.list-accdb-files.outputs.hasAccdbFiles }}
        run: |
          sudo npm i -g csvtojson

      - name: Find accessdb files
        id: accessfiles
        if: ${{ steps.list-accdb-files.outputs.hasAccdbFiles }}
        run: |
          result=$(${{ github.workspace }}/.github/workflows/diff-accdb-files.sh \
            ${{ github.event.pull_request.head.sha }} \
            | ${{ github.workspace }}/.github/workflows/convert-to-markdown-comment.sh \
            | jq --slurp --raw-input '.')
          echo "::set-output name=result::$result"

      - name: Add diff comment to pull request
        id: add-comment
        if: ${{ steps.list-accdb-files.outputs.hasAccdbFiles }}
        env:
          DIFF: ${{ steps.accessfiles.outputs.result }}
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST -d '{"body": ${{ env.DIFF }}}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
