name: Say Hello World
on: push

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Find accessdb files
        run: |
          result=$(git status)
          echo "$result"

