name: Say Hello World
on: push

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x

      - name: Build API project
        run: dotnet publish $GITHUB_WORKSPACE/SolutionCliTools/ -o $GITHUB_WORKSPACE/bin -c release -r ubuntu.18.04-x64 --self-contained

      - name: Find accessdb files
        id: access-files
        run: |
          $GITHUB_WORKSPACE/.github/workflows/command.sh HEAD
        continue-on-error: true

